/*type etablissement*/
INSERT INTO `mydb`.`type` (`denomination`) VALUES ('Administration');
INSERT INTO `mydb`.`type` (`denomination`) VALUES ('Corporate');
INSERT INTO `mydb`.`type` (`denomination`) VALUES ('Franchise');
INSERT INTO `mydb`.`type` (`denomination`) VALUES ('Professionel');

/*etablissement*/
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Siege Social', 'indisponible', '1', '6');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Saint-Denis', '(438) 380-5624', '2', '6');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Angus', '(438) 384-7225', '2', '5');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Fleury', '(438) 385-1602', '2', '4');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Notre-Dame', '(514) 303-1511', '2', '3');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Île-des-Sœurs', '(514) 508-8800', '2', '2');
INSERT INTO `mydb`.`etablissement` (`name`, `tel`, `type_id`, `Adresse_id`) VALUES ('Van Horne', '(514) 750-7245', '2', '1');


/*table role*/
INSERT INTO `mydb`.`role` (`denomination`) VALUES ('Admin');
INSERT INTO `mydb`.`role` (`denomination`) VALUES ('Chef Boulanger');
INSERT INTO `mydb`.`role` (`denomination`) VALUES ('Gérant');
INSERT INTO `mydb`.`role` (`denomination`) VALUES ('Cuisinier');
INSERT INTO `mydb`.`role` (`denomination`) VALUES ('Vendeur');


/*adresse*/
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('1291', ' avenue Van Horne', 'Outremont', 'Quebec', ' H2V 1K7', 'Canada');
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('105', 'Chemin de la Pointe Nord', 'Verdun', 'Quebec', 'H3E 0B5', 'Canada');
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('2660', 'rue Notre-Dame Ouest', 'Montréal', 'Quebec', 'H3J 1N7', 'Canada');
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('1602', 'rue Fleury Est', 'Montréal', 'Quebec', 'H2C 1S8', 'Canada');
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('4093', 'rue Molson', 'Montréal', 'Quebec', 'H1Y 3L1', 'Canada');
INSERT INTO `mydb`.`adresse` (`numero_rue`, `nom_rue`, `ville`, `province`, `code_postal`, `pays`) VALUES ('3660', 'rue Saint-Denis', 'Montréal', 'Quebec', 'H2X 3L7', 'Canada');



/*categorie*/
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Pain Blanc');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Pain blanc garni');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('bretzel');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Brioche');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Pains spéciaux');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('challah');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Produits saisonniers');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Pains au levain');
INSERT INTO `mydb`.`categorie` (`denomination`) VALUES ('Pains viennois');
/*produit*/
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('FICELLE PAVOT', '2', 'Notre meilleur vendeur. Ficelle à la farine Mamie Clafoutis biologique, avec du gros sel, des graines de pavot et sésame', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('FOUGASSE', '2', 'Fougasse aux olives noires et vertes entières, aux herbes de Provence', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('MICHE BLANCHE', '1', 'Miche faite avec notre farine exclusive biologique Mamie Clafoutis par La Milanaise', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE HERBES', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('FICELLE BLEU', '2', 'Un très gros vendeur au fromage bleu. Idéal pour l\'apéritif ou le dîner', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PANINI NOIX', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ÉPI', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PARISIEN', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CIABATTA ', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ETOILES FARINÉES', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CIABATTA OLIVES', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE CHORIZO', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE OLIVES', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE POIREAUX CHEDDAR', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE DE CRISSE', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE AIL', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE CHEVRE TOMATE', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE POIVRONS FETA', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE OLIVES OIGNONS', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE CHAMPI CHEDDAR', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PETIT RUSTIQUE', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE SÉSAME', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE BACON MOUTARDE', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAGUETTE TORSADÉE', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ETOILES PAVOT', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAGUETTES COEUR', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PAIN FROMAGE CHEDDAR', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE CHEVRE MIEL CANNEBERGE', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FOCCACIA OLIVE TOMATE MOZZA', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('LAPIN BAGUETTE ', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CIABATTA NATURE', '1', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CIABATTA TOURNESOL', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CIABATTA SÉSAME', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FICELLE SMOKED MEAT', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FOUGASSETTE BACON CHEDDAR', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('FOCCACIA AUX HERBES', '2', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRETZELS ', '3', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('BRETZEL FROMAGE', '3', 'Un magnifique bretzel au cheddar vieilli, pour un en-cas sur le pouce', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE PETITE', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('BRIOCHE GROSSE', '4', 'Une belle brioche pour le petit déjeuner en famille du dimanche, pur beurre,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE DEMIE', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE PISTACHE', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE COURONNE CHOCO', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE COURONNE FRUITS CONFITS', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('TROPEZIENNE', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('TROPEZIENNE GRANDE', '4', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BRIOCHE CARÊME', '4', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('PETIT CAMP', '5', 'Un pain de campagne traditionnel aux farines biologiques de seigle et de mélange Mamie Clafoutis ', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('GROS CAMP', '5', 'Un pain de campagne traditionnel aux farines biologiques de seigle et de mélange Mamie Clafoutis , pour une famille nombreuse ou pour faire la semaine,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('BAG CAMP', '5', 'Pour ceux qui veulent un pain de campagne à 2,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL CAMPAGNE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CARRÉ RAISINS', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('DEMI RAISINS CANNELLE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CHALLAH', '6', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('ÉPEAUTRE', '5', 'L\'épeautre est une céréale ancienne au bon goût de noix,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('MICHE INTÉGRALE', '5', 'La solution santé avec un pain fait de farine qui a conservé toutes ses propriétés nutritionnelles,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('TOURNESOL', '5', 'Pour ceux qui veulent un pain intégral avec un goût un peu plus intéressant.', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAG INTÉGRALE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('KHORASAN', '5', 'La farine de khorasan est une variété de céréale ancienne et biologique,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAG KHORASAN', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PETITS KOUGLOFS', '7', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('GROS KOUGLOFS', '7', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('LAMALA', '7', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('NOIX', '8', 'Un pain avec des noix entières, idéal avec du fromage', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('OLIVE', '8', 'Un pain fait du mélange exclusif biologique Mamie Clafoutis, avec des olives entières, idéal par exemple avec de la charcuterie', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CHIA, RAISIN, POMME', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('9 GRAINS', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAG 9 GRAINS', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BAG LEVAIN', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('RANDONNEUR', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('LEVAIN CANNEBERGE', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('LEVAIN FIGUES', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BELGE', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CARRÉ LEVAIN CURCUMA', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL NOIX', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL CANNEBERGE', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL 9 GRAINS', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PAIN ABRICOT NOISETTE ', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PAIN VITAMINÉ', '8', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('MICHE MAMIE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PETITE MAMIE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PUMPERNICKEL', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('PAIN SANS GLUTEN', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('100% SEIGLE', '5', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('VIENNOIS LONG', '9', 'un bon petit pain long de type brioché, idéal pour le goûter des enfants,', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `description`, `poid`, `unite`) VALUES ('CARRÉ LAIT', '9', 'Le pain brioché idéal pour le week-end, plus léger que la brioche ', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BURGER', '9', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('VIENNOIS CHOC ', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BURGER OIGNONS ', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BURGER CHEDDAR', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BURGER KETCHUP', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('LAPIN-ST NICOLAS', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('CŒUR-BONHOMME-CRI', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('MINI BURGER', '9', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('BURGER SÉSAME', '9', '1', 'Unite');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('ROLL VIENNOIS', '9', '0.15', 'KG');
INSERT INTO `mydb`.`produit` (`nom`, `categorie_id`, `poid`, `unite`) VALUES ('VIENNOIS CHOCOLAT BLANC CANNEBERGES', '9', '0.15', 'KG');

	/*ingrédient*/
	INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('blancheIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('intégraleIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('campagneIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('levainIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('MamieIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('viennoisIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('briocheIngrédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('levaindurIngédient');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('eau bassinage');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('eau');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine Mamie');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine tamisée');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('seigle ');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('seigle torréfié');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('orge torréfié');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine blé entier');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine 4141');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine khorasan blanche');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine khorasan entière');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('farine épeautre');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('sel');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('levure');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('noix');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('chorizo');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('tournesol');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('huile olive');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('olive');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('herbe provence');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('canneberge');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('céréales');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('pomme');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('raisins');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('raisins macérés');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('graine chia');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('pavot');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('miel');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('abricot');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('noisette');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('mélange rando');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('figues');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('poudre de lait');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('lait');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('sucre');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('beurre');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('œuf');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('oignons');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('chocolat');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('vanille');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('fleur d\'oranger');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('rhum');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('cannelle');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('cheddar');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('ketchup');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('mélange tomate curcuma');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('graines de lin');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('graines de citrouille');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('moutarde');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('moutarde ancienne');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('bacon');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('Mélange graines germées');
INSERT INTO `mydb`.`ingredient` (`denomination`) VALUES ('chocolat blanc');
