-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 17:20:10 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`adresse` ;

CREATE TABLE IF NOT EXISTS `mydb`.`adresse` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `numero_rue` INT(11) NOT NULL,
  `nom_rue` VARCHAR(255) NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `province` VARCHAR(255) NOT NULL,
  `code_postal` VARCHAR(255) NOT NULL,
  `pays` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idAdresse_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtype_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`etablissement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`etablissement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`etablissement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL DEFAULT 'Mami Clafoutis',
  `adresse` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(12) NOT NULL,
  `type_id` INT(11) NOT NULL,
  `Adresse_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idetablisement_UNIQUE` (`id` ASC),
  UNIQUE INDEX `adresse_UNIQUE` (`adresse` ASC),
  UNIQUE INDEX `tel_UNIQUE` (`tel` ASC),
  INDEX `fk_etablisement_type_idx` (`type_id` ASC),
  INDEX `fk_etablisement_Adresse1_idx` (`Adresse_id` ASC),
  CONSTRAINT `fk_etablisement_Adresse1`
    FOREIGN KEY (`Adresse_id`)
    REFERENCES `mydb`.`adresse` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etablisement_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;

CREATE TABLE IF NOT EXISTS `mydb`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `prenom` VARCHAR(255) NOT NULL,
  `etablissement_id` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL,
  `userName` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUser_UNIQUE` (`id` ASC),
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC),
  INDEX `fk_User_etablisement1_idx` (`etablissement_id` ASC),
  INDEX `fk_utilisateur_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_User_etablisement1`
    FOREIGN KEY (`etablissement_id`)
    REFERENCES `mydb`.`etablissement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `utilisateur_id` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  `valide` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_commande_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_commande_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredient` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(255) NOT NULL,
  `quantite` INT(11) NOT NULL,
  `unite_ingredient` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `denomination_UNIQUE` (`denomination` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produit` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `categorie_id` INT(11) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `prix` FLOAT NOT NULL,
  `url_image` VARCHAR(255) NULL DEFAULT NULL,
  `estvisible` TINYINT(1) NOT NULL,
  `reference` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idproduit_UNIQUE` (`id` ASC),
  INDEX `fk_produit_categorie1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_produit_categorie1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `mydb`.`categorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_de_commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ligne_de_commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ligne_de_commande` (
  `commande_id` INT(11) NOT NULL,
  `produit_idproduit` INT(11) NOT NULL,
  `quantite` INT(11) NOT NULL,
  PRIMARY KEY (`commande_id`, `produit_idproduit`),
  INDEX `fk_ligne de commande_produit1_idx` (`produit_idproduit` ASC),
  CONSTRAINT `fk_ligne de commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne de commande_produit1`
    FOREIGN KEY (`produit_idproduit`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ligne_ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ligne_ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ligne_ingredient` (
  `ingredient_id` INT(11) NOT NULL,
  `produit_id` INT(11) NOT NULL,
  `quantite` FLOAT NOT NULL,
  `unite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ingredient_id`, `produit_id`),
  INDEX `fk_ligne ingredient_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_ligne ingredient_ingredient1`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `mydb`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne ingredient_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`production`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`production` ;

CREATE TABLE IF NOT EXISTS `mydb`.`production` (
  `utilisateur_id` INT(11) NOT NULL,
  `produit_id` INT(11) NOT NULL,
  `quantite` INT(11) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `produit_id`, `date`),
  INDEX `fk_production_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_production_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_production_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`recette`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recette` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recette` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produit_id` INT(11) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date` DATETIME NOT NULL,
  `date_modif` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_recette_produit1` (`produit_id` ASC),
  CONSTRAINT `fk_recette_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ventes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ventes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ventes` (
  `date_horaire` DATETIME NOT NULL,
  `utilisateur_id` INT(11) NOT NULL,
  `quantite` INT(11) NOT NULL,
  `produit_id` INT(11) NOT NULL,
  PRIMARY KEY (`produit_id`, `utilisateur_id`, `date_horaire`),
  INDEX `fk_ventes_utilisateur1_idx` (`utilisateur_id` ASC),
  INDEX `fk_ventes_produit1_idx` (`produit_id` ASC),
  CONSTRAINT `fk_ventes_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `mydb`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventes_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
